### ISSUE TITLE
默认超时时间1000*360无效

### ISSUE THREAD

**Issue by joenhon** [ZhiYiDai/Ffast-FE#4]
超时时间默认是那么多 如果我没有看错应该是 360秒 为什么不到3秒就提示超时？

**Comment by ZhiYiDai** [comment]
你请求哪个接口呢 看看是不是你接口的问题

**Comment by joenhon** [comment]
this.$http.apiPost

**Comment by joenhon** [comment]
![image](https://user-images.githubusercontent.com/39330202/56949740-3b76fa00-6b66-11e9-9d95-f2034386ba3d.png)

**Comment by ZhiYiDai** [comment]
不排除是axiosBUG导致的可以更新下axios版本试试，但是你这样循环请求多多少少会产生一些问题，建议改成统一请求，
把审核订单ID放数组统一发请求到后端。

**Comment by joenhon** [comment]
好的

**Comment by ZhiYiDai** [comment]
HttpUtils.js  下面 apiPost请求如果请求失败会调用请求超时timeoutMsg();，这个实际是你后端接口问题，你这样循环请求导致服务器处理过慢导致的请求超时。
